const mainCacesData = [
  {
    id: 1,
    case: 'AR - 0123',
    area: '94 м2',
    rooms: '3',
    year: '2020',
    title_ua: 'ЖК NEW YORK CONCEPT HOUSE',
    title_ru: 'ЖК NEW YORK CONCEPT HOUSE',
    title_en: 'ЖК NEW YORK CONCEPT HOUSE',
    description_ua: "Дизайн інтер'єру квартири",
    description_ru: "Дизайн інтер'єру квартири",
    description_en: "Дизайн інтер'єру квартири",
  },
  {
    id: 2,
    case: 'AR - 0123',
    area: '94 м2',
    rooms: '3',
    year: '2020',
    title_ua: 'ЖК Campus',
    title_ru: 'ЖК Campus',
    title_en: 'ЖК Campus',
    description_ua: "Дизайн інтер'єру квартири",
    description_ru: "Дизайн інтер'єру квартири",
    description_en: "Дизайн інтер'єру квартири",
  },
  {
    id: 3,
    case: 'AR - 0123',
    area: '94 м2',
    rooms: '3',
    year: '2020',
    title_ua: 'ЖК Campus',
    title_ru: 'ЖК Campus',
    title_en: 'ЖК Campus',
    description_ua: "Дизайн інтер'єру квартири",
    description_ru: "Дизайн інтер'єру квартири",
    description_en: "Дизайн інтер'єру квартири",
  },
  {
    id: 4,
    case: 'AR - 0123',
    area: '94 м2',
    rooms: '3',
    year: '2020',
    title_ua: 'ЖК Campus',
    title_ru: 'ЖК Campus',
    title_en: 'ЖК Campus',
    description_ua: "Дизайн інтер'єру квартири",
    description_ru: "Дизайн інтер'єру квартири",
    description_en: "Дизайн інтер'єру квартири",
  },
  {
    id: 5,
    case: 'AR - 0123',
    area: '94 м2',
    rooms: '3',
    year: '2020',
    title_ua: 'ЖК Campus',
    title_ru: 'ЖК Campus',
    title_en: 'ЖК Campus',
    description_ua: "Дизайн інтер'єру квартири",
    description_ru: "Дизайн інтер'єру квартири",
    description_en: "Дизайн інтер'єру квартири",
  },
  {
    id: 6,
    case: 'AR - 0123',
    area: '94 м2',
    rooms: '3',
    year: '2020',
    title_ua: 'ЖК Campus',
    title_ru: 'ЖК Campus',
    title_en: 'ЖК Campus',
    description_ua: "Дизайн інтер'єру квартири",
    description_ru: "Дизайн інтер'єру квартири",
    description_en: "Дизайн інтер'єру квартири",
  },
  {
    id: 7,
    case: 'AR - 0123',
    area: '94 м2',
    rooms: '3',
    year: '2020',
    title_ua: 'ЖК Campus',
    title_ru: 'ЖК Campus',
    title_en: 'ЖК Campus',
    description_ua: "Дизайн інтер'єру квартири",
    description_ru: "Дизайн інтер'єру квартири",
    description_en: "Дизайн інтер'єру квартири",
  },
];

export default mainCacesData;
