export const portfolioData = {
  portfolio_items: [
    {
      id: 1,
      project_name_ua: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_ru: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_en: 'ЖК NEW YORK CONCEPT HOUSE',
      sub_title_ua: "Дизайн інтер'єру квартири",
      sub_title_ru: "Дизайн інтер'єру квартири",
      sub_title_en: "Дизайн інтер'єру квартири",
      slug: '/portfolio-inner/',
      image: '../../../../image41.jpg',
      awords: false,
      type: '50-100',
      project_number: '123',
    },
    {
      id: 2,
      project_name_ua: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_ru: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_en: 'ЖК NEW YORK CONCEPT HOUSE',
      sub_title_ua: "Дизайн інтер'єру квартири",
      sub_title_ru: "Дизайн інтер'єру квартири",
      sub_title_en: "Дизайн інтер'єру квартири",
      slug: '/portfolio-inner/',
      image: '../../../../image41.jpg',
      awords: true,
      type: '50-100',
      project_number: '123',
    },
    {
      id: 3,
      project_name_ua: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_ru: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_en: 'ЖК NEW YORK CONCEPT HOUSE',
      sub_title_ua: "Дизайн інтер'єру квартири",
      sub_title_ru: "Дизайн інтер'єру квартири",
      sub_title_en: "Дизайн інтер'єру квартири",
      slug: '/portfolio-inner/',
      image: '../../../../image41.jpg',
      awords: false,
      type: '50-100',
      project_number: '123',
    },
    {
      id: 4,
      project_name_ua: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_ru: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_en: 'ЖК NEW YORK CONCEPT HOUSE',
      sub_title_ua: "Дизайн інтер'єру квартири",
      sub_title_ru: "Дизайн інтер'єру квартири",
      sub_title_en: "Дизайн інтер'єру квартири",
      slug: '/portfolio-inner/',
      image: '../../../../image41.jpg',
      awords: false,
      type: '50-100',
      project_number: '123',
    },
    {
      id: 5,
      project_name_ua: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_ru: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_en: 'ЖК NEW YORK CONCEPT HOUSE',
      sub_title_ua: "Дизайн інтер'єру квартири",
      sub_title_ru: "Дизайн інтер'єру квартири",
      sub_title_en: "Дизайн інтер'єру квартири",
      slug: '/portfolio-inner/',
      image: '../../../../gallery/image41.jpg',
      awords: true,
      type: '50-100',
      project_number: '123',
    },
    {
      id: 6,
      project_name_ua: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_ru: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_en: 'ЖК NEW YORK CONCEPT HOUSE',
      sub_title_ua: "Дизайн інтер'єру квартири",
      sub_title_ru: "Дизайн інтер'єру квартири",
      sub_title_en: "Дизайн інтер'єру квартири",
      slug: '/portfolio-inner/',
      image: '../../../../gallery/image41.jpg',
      awords: false,
      type: '50-100',
      project_number: '123',
    },
    {
      id: 7,
      project_name_ua: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_ru: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_en: 'ЖК NEW YORK CONCEPT HOUSE',
      sub_title_ua: "Дизайн інтер'єру квартири",
      sub_title_ru: "Дизайн інтер'єру квартири",
      sub_title_en: "Дизайн інтер'єру квартири",
      slug: '/portfolio-inner/',
      image: '../../../../gallery/image41.jpg',
      awords: false,
      type: '100-1500',
      project_number: '123',
    },
    {
      id: 8,
      project_name_ua: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_ru: 'ЖК NEW YORK CONCEPT HOUSE',
      project_name_en: 'ЖК NEW YORK CONCEPT HOUSE',
      sub_title_ua: "Дизайн інтер'єру квартири",
      sub_title_ru: "Дизайн інтер'єру квартири",
      sub_title_en: "Дизайн інтер'єру квартири",
      slug: '/portfolio-inner/',
      image: '../../../../gallery/image41.jpg',
      awords: false,
      type: '100-1500',
      project_number: '123',
    },
  ],
};
